name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build - Windows x64
      run: dotnet publish --configuration Release --no-restore -r win-x64 /p:PublishSingleFile=true
    - name: Build - Ubuntu x64
      run: dotnet publish --configuration Release --no-restore -r ubuntu-x64 /p:PublishSingleFile=true
    - name: Build - OSX x64
      run: dotnet publish --configuration Release --no-restore -r osx-x64 /p:PublishSingleFile=true
