name: .NET Core - Release

on:
  push:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build - Common Lib
      run: dotnet publish --configuration Release --no-restore
      working-directory: ./LibCpp2IL/
    - name: Build - Windows x64
      working-directory: ./Cpp2IL/
      run: dotnet publish --configuration Release --no-restore -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
    - name: Build - Ubuntu x64
      working-directory: ./Cpp2IL/
      run: dotnet publish --configuration Release --no-restore -r ubuntu-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
    - name: Build - OSX x64
      working-directory: ./Cpp2IL/
      run: dotnet publish --configuration Release --no-restore -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
    - name: Upload Common Lib Files
      uses: actions/upload-artifact@v2
      with:
        name: LibCpp2IL
        path: ./LibCpp2IL/bin/Release/netstandard2.1/publish/LibCpp2IL*
    - name: Upload Win x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Win
        path: ./Cpp2IL/bin/Release/net5.0/win-x64/publish/Cpp2IL.exe
    - name: Upload Ubuntu x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Linux
        path: ./Cpp2IL/bin/Release/net5.0/ubuntu-x64/publish/Cpp2IL
    - name: Upload OSX x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Mac
        path: ./Cpp2IL/bin/Release/net5.0/osx-x64/publish/Cpp2IL
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: commit_${{ github.sha }}
        release_name: Commit ${{ github.sha }}
        draft: false
        prerelease: false
    - name: Release Windows Build
      id: release-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Cpp2IL/bin/Release/net5.0/win-x64/publish/Cpp2IL.exe
        asset_name: Cpp2IL-Win.exe
        asset_content_type: application/octet-stream
    - name: Release Linux Build
      id: release-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Cpp2IL/bin/Release/net5.0/ubuntu-x64/publish/Cpp2IL
        asset_name: Cpp2IL-Linux
        asset_content_type: application/octet-stream
    - name: Release OSX Build
      id: release-osx
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Cpp2IL/bin/Release/net5.0/osx-x64/publish/Cpp2IL
        asset_name: Cpp2IL-OSX
        asset_content_type: application/octet-stream
